2024-10-30 18:27:34,538 - client_logger - ERROR - Connection failed: Error: [WinError 10061] No connection could be made because the target machine actively refused it [File: client_tcp.py, Line: 42, Function: connect]
2024-10-30 18:27:38,579 - client_logger - ERROR - Connection failed: Error: [WinError 10061] No connection could be made because the target machine actively refused it [File: client_tcp.py, Line: 42, Function: connect]
2024-10-30 18:27:42,623 - client_logger - ERROR - Connection failed: Error: [WinError 10061] No connection could be made because the target machine actively refused it [File: client_tcp.py, Line: 42, Function: connect]
2024-10-30 18:27:46,656 - client_logger - ERROR - Connection failed: Error: [WinError 10061] No connection could be made because the target machine actively refused it [File: client_tcp.py, Line: 42, Function: connect]
2024-10-30 18:27:53,689 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 18:27:53,694 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 18:28:51,987 - server_logger - ERROR - Socket setup failed. Error: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted [File: server_tcp.py, Line: 70, Function: setup_socket]
2024-10-30 18:29:11,052 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 18:29:11,057 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 18:30:21,751 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 18:31:10,007 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 18:31:10,011 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 18:34:39,474 - client_logger - ERROR - Failed to send message due to socket error. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 104, Function: build_and_send_message]
2024-10-30 18:35:23,921 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 18:35:23,923 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 18:40:02,124 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 18:40:02,130 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 18:40:12,947 - client_logger - ERROR - Failed to send message due to socket error. Error: [WinError 10053] An established connection was aborted by the software in your host machine [File: client_tcp.py, Line: 104, Function: build_and_send_message]
2024-10-30 18:40:12,951 - client_logger - ERROR - Login failed due to connection error: [WinError 10053] An established connection was aborted by the software in your host machine [File: client_tcp.py, Line: 141, Function: login]
2024-10-30 18:43:41,316 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 18:43:41,741 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 18:43:41,746 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 18:44:53,174 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 18:44:53,614 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 18:44:53,619 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 18:45:20,956 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 18:48:28,710 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 18:48:28,715 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 18:51:43,662 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 18:51:47,705 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 18:51:47,710 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 18:55:22,052 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 18:56:21,065 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 18:56:21,070 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 19:06:02,931 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 19:06:06,545 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 19:06:06,550 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 19:08:32,229 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 19:08:32,656 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 19:08:32,661 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 19:09:04,266 - client_logger - ERROR - Failed to send message due to socket error. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 104, Function: build_and_send_message]
2024-10-30 19:09:04,270 - client_logger - ERROR - Failed to connect to 127.0.0.1:5678. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 70, Function: recv_message_and_parse]
2024-10-30 19:09:23,873 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 19:09:23,878 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 19:12:40,687 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 19:12:56,375 - client_logger - ERROR - Connection failed: Error: [WinError 10061] No connection could be made because the target machine actively refused it [File: client_tcp.py, Line: 42, Function: connect]
2024-10-30 19:13:00,432 - client_logger - ERROR - Connection failed: Error: [WinError 10061] No connection could be made because the target machine actively refused it [File: client_tcp.py, Line: 42, Function: connect]
2024-10-30 19:13:03,036 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 19:13:03,042 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 19:13:19,067 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 19:14:43,412 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 19:14:48,270 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 19:14:48,697 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 19:14:48,760 - server_logger - ERROR - Unexpected error: 'NoneType' object has no attribute 'split' [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 19:14:51,432 - client_logger - ERROR - Failed to send message due to socket error. Error: [WinError 10038] An operation was attempted on something that is not a socket [File: client_tcp.py, Line: 104, Function: build_and_send_message]
2024-10-30 19:14:59,008 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 19:14:59,013 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 19:18:39,069 - server_logger - ERROR - Socket setup failed. Error: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted [File: server_tcp.py, Line: 70, Function: setup_socket]
2024-10-30 19:19:11,786 - server_logger - ERROR - Socket setup failed. Error: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted [File: server_tcp.py, Line: 70, Function: setup_socket]
2024-10-31 10:46:55,061 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-31 10:46:55,063 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-31 10:47:57,267 - server_logger - ERROR - Unexpected error: 'NoneType' object has no attribute 'split' [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-31 10:48:09,226 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 146, Function: load_user_database]
2024-10-31 10:48:09,232 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 92, Function: load_questions]
2024-10-31 10:50:38,170 - server_logger - ERROR - Unexpected error: 'NoneType' object has no attribute 'split' [File: server_tcp.py, Line: 445, Function: handle_client_message]
2024-10-31 10:54:05,291 - server_logger - ERROR - Unexpected error: handle_question_message() missing 1 required positional argument: 'username' [File: server_tcp.py, Line: 445, Function: handle_client_message]
2024-10-31 11:08:41,130 - client_test - ERROR - Failed to connect to 127.0.0.1:5678. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 70, Function: recv_message_and_parse]
2024-10-31 11:12:57,582 - client_test - ERROR - Failed to connect to 127.0.0.1:5678. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 70, Function: recv_message_and_parse]
2024-10-31 11:20:40,127 - client_test - ERROR - Failed to send message due to socket error. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 104, Function: build_and_send_message]
2024-10-31 11:24:54,241 - client_test - ERROR - Failed to connect to 127.0.0.1:5678. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 70, Function: recv_message_and_parse]
2024-10-31 11:27:05,711 - client_test - ERROR - Failed to send message due to socket error. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 104, Function: build_and_send_message]
2024-10-31 11:27:05,714 - client_test - ERROR - Failed to connect to 127.0.0.1:5678. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 70, Function: recv_message_and_parse]
2024-10-31 11:27:18,820 - client_logger - ERROR - Connection failed: Error: [WinError 10061] No connection could be made because the target machine actively refused it [File: client_tcp.py, Line: 42, Function: connect]
2024-10-31 11:27:22,866 - client_logger - ERROR - Connection failed: Error: [WinError 10061] No connection could be made because the target machine actively refused it [File: client_tcp.py, Line: 42, Function: connect]
2024-10-31 11:27:26,911 - client_logger - ERROR - Connection failed: Error: [WinError 10061] No connection could be made because the target machine actively refused it [File: client_tcp.py, Line: 42, Function: connect]
2024-10-31 11:40:22,236 - client_test - ERROR - Failed to send message due to socket error. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 104, Function: build_and_send_message]
2024-10-31 11:48:55,968 - client_test - ERROR - Failed to connect to 127.0.0.1:5678. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 70, Function: recv_message_and_parse]
2024-10-31 12:13:05,265 - client_test - ERROR - Failed to connect to 127.0.0.1:5678. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 70, Function: recv_message_and_parse]
2024-10-31 12:22:08,553 - client_test - ERROR - Failed to connect to 127.0.0.1:5678. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 70, Function: recv_message_and_parse]
2024-10-31 12:26:37,352 - client_test - ERROR - Failed to connect to 127.0.0.1:5678. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 70, Function: recv_message_and_parse]
2024-10-31 12:28:43,652 - client_test - ERROR - Failed to connect to 127.0.0.1:5678. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 70, Function: recv_message_and_parse]
